<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net472</TargetFramework>
    <EnableNETAnalyzers>True</EnableNETAnalyzers>
    <RunAnalyzersDuringBuild>True</RunAnalyzersDuringBuild>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <CodeAnalysisRuleSet />
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <CodeAnalysisRuleSet />
  </PropertyGroup>

  <ItemGroup>
    <SpecFlowObsoleteCodeBehindFiles Remove="Features\Cart - Copy.feature.cs" />
    <SpecFlowObsoleteCodeBehindFiles Remove="Features\Login - Copy.feature.cs" />
    <SpecFlowObsoleteCodeBehindFiles Remove="Features\Login2 - Copy.feature.cs" />
    <SpecFlowObsoleteCodeBehindFiles Remove="Features\Logout - Copy.feature.cs" />
    <SpecFlowObsoleteCodeBehindFiles Remove="Features\SideBar - Copy.feature.cs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="log4net" Version="2.0.15" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" Version="17.4.0" />
    <PackageReference Include="MSTest.TestAdapter" Version="2.2.10" />
    <PackageReference Include="MSTest.TestFramework" Version="3.0.0" />
    <PackageReference Include="Selenium.Support" Version="2.53.1" />
    <PackageReference Include="Selenium.WebDriver" Version="2.53.1" />
    <PackageReference Include="Selenium.WebDriver.ChromeDriver" Version="109.0.5414.7400" />
    <PackageReference Include="SpecFlow.Assist.Dynamic" Version="1.4.2" />
    <PackageReference Include="SpecFlow.MsTest" Version="3.9.74" />
    <PackageReference Include="SpecFlow.Plus.LivingDocPlugin" Version="3.9.57" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
  <ItemGroup>
    <Compile Update="Features\Search.feature.cs">
      <DependentUpon>Search.feature</DependentUpon>
    </Compile>
    <Compile Update="Features\Home.feature.cs">
      <DependentUpon>Home.feature</DependentUpon>
    </Compile>
    <Compile Update="Features\Cart.feature.cs">
      <DependentUpon>Cart.feature</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="Drivers\chromedriver.exe">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="log4net.config">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
    <None Update="specflow.json">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <SpecFlowFeatureFiles Update="Features\Search.feature">
      <Visible>$(UsingMicrosoftNETSdk)</Visible>
      <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
    </SpecFlowFeatureFiles>
    <SpecFlowFeatureFiles Update="Features\Home.feature">
      <Visible>$(UsingMicrosoftNETSdk)</Visible>
      <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
    </SpecFlowFeatureFiles>
    <SpecFlowFeatureFiles Update="Features\Cart.feature">
      <Visible>$(UsingMicrosoftNETSdk)</Visible>
      <CodeBehindFile>%(RelativeDir)%(Filename).feature$(DefaultLanguageSourceExtension)</CodeBehindFile>
    </SpecFlowFeatureFiles>
  </ItemGroup>

</Project>